### ISSUE TITLE
ESP Biticino scs bus

### ISSUE THREAD

**Issue by MattWestb** [stapelberg/intercom-backpack#1]
Have you thinking porting the code to ESPHome ?
I have one device and 32 neighbors and like getting it easy integrated in HA but dont have the code experience for do it only the hardware hacking im good on (like Zigbee hardware and so on).
Thanks in advance.

MW

**Comment by stapelberg** [comment]
I have no plans to port this code to ESPhome.

If you don’t have the experience, I suggest finding a local makerspace, hackerspace or fablab. The community there will be able to help you with such electronics projects.

**Comment by MattWestb** [comment]
Servus Michael.

Thanks for replaying. I continue looking around and see if i can finding some usebal code then you have getting all the hardware in place (I think i have taken the power on the cap if its is 5V and not on the small pins on one IC).

Mvh Mattias W
